name: jobs examples

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: correcao do build failed.
        run: echo Hello, World! Build failed.
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: step do deploy
        run: echo Hello, world! Deploy.
